version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: dev_db 
      POSTGRES_USER: main_user 
      POSTGRES_PASSWORD: password123 
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data: